// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// export_ecg_impl
void export_ecg_impl(NumericVector x, std::string& path);
RcppExport SEXP phyr6_export_ecg_impl(SEXP xSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string& >::type path(pathSEXP);
    export_ecg_impl(x, path);
    return R_NilValue;
END_RCPP
}
