# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

export_ecg_impl <- function(x, path) {
    invisible(.Call('phyr6_export_ecg_impl', PACKAGE = 'phyr6', x, path))
}

